services:
  geant4-lab:
    build: .
    image: geant4-modern-lab:latest
    container_name: physics_lab
    
    volumes:
      - ./:/home/student/work
      - /tmp/.X11-unix:/tmp/.X11-unix  #GUI
    
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
    

    stdin_open: true
    tty: true
